/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Cards: typeof import('./src/components/datasource/cards.vue')['default']
    Chat: typeof import('./src/components/community/chat.vue')['default']
    Datashow: typeof import('./src/components/datashow/index.vue')['default']
    Detail: typeof import('./src/components/datasource/Detail.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    LoginPage: typeof import('./src/components/welcome/LoginPage.vue')['default']
    MainContent: typeof import('./src/components/welcome/MainContent.vue')['default']
    NameChat: typeof import('./src/components/community/nameChat.vue')['default']
    Publish: typeof import('./src/components/datasource/Publish.vue')['default']
    RegisterPage: typeof import('./src/components/welcome/RegisterPage.vue')['default']
    Resourceview: typeof import('./src/components/datasource/resourceview.vue')['default']
    ResourceviewBack: typeof import('./src/components/datasource/resourceviewBack.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Seats: typeof import('./src/components/datasource/seats.vue')['default']
    Sliding: typeof import('./src/components/welcome/Sliding.vue')['default']
    Switch: typeof import('./src/components/controller/switch.vue')['default']
    Usercontroller: typeof import('./src/components/controller/usercontroller.vue')['default']
  }
}
