server:
  port: 8080
spring:
  datasource:
    username: xxx
    password: xxx
    url: xxx
    driver-class-name: com.mysql.jdbc.Driver
  mail:
    default-encoding: UTF-8
    host: xxx
    username: xxx
    password: xxx
